apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: my-path
    includeSelectors: false
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - migrate-job.yaml
  - api.yaml
  - web.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - ingress.yaml
images:
  - name: my-path-api
    newName: ghcr.io/OWNER/my-path-api
    newTag: latest
  - name: my-path-web
    newName: ghcr.io/OWNER/my-path-web
    newTag: latest
