"""initial schema

Revision ID: b2a8d1a85856
Revises:
Create Date: 2026-09-22 13:55:06.805898

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2a8d1a85856"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total_records", sa.Integer(), nullable=False),
        sa.Column("flagged_count", sa.Integer(), nullable=False),
        sa.Column("drafted_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)

    op.create_table(
        "flags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=64), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("program", sa.String(length=255), nullable=False),
        sa.Column("record", sa.JSON(), nullable=False),
        sa.Column("barrier_types", sa.JSON(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("barrier_count", sa.Integer(), nullable=False),
        sa.Column("days_to_drop", sa.Integer(), nullable=False),
        sa.Column("source_fields", sa.JSON(), nullable=False),
        sa.Column("route_to", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("original_draft", sa.Text(), nullable=True),
        sa.Column("draft_message", sa.Text(), nullable=True),
        sa.Column("draft_source", sa.String(length=16), nullable=True),
        sa.Column("draft_language", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dismiss_reason", sa.Text(), nullable=True),
        sa.Column("routed_to", sa.String(length=32), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("flags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flags_program"), ["program"], unique=False)
        batch_op.create_index("ix_flags_run_status", ["run_id", "status"], unique=False)
        batch_op.create_index("ix_flags_run_urgency", ["run_id", "days_to_drop"], unique=False)

    op.create_table(
        "action_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("flag_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("coach", sa.String(length=128), nullable=False),
        sa.Column("before_text", sa.Text(), nullable=True),
        sa.Column("after_text", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["flag_id"], ["flags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_action_logs_flag_id"), ["flag_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_logs_flag_id"))

    op.drop_table("action_logs")
    with op.batch_alter_table("flags", schema=None) as batch_op:
        batch_op.drop_index("ix_flags_run_urgency")
        batch_op.drop_index("ix_flags_run_status")
        batch_op.drop_index(batch_op.f("ix_flags_program"))

    op.drop_table("flags")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))

    op.drop_table("runs")
    # ### end Alembic commands ###
